/**
 * Frontend Master 18-Category Specification with Emojis & Subcategories
 */
export const CATEGORIES = [
  {
    id: 'books-study',
    name: 'Books & Study',
    emoji: '📚',
    description: 'Textbooks, reference books, notes, question banks, academic guides',
    subcategories: [
      'Textbooks',
      'Reference Books',
      'Handwritten Notes',
      'Question Banks & PYQs',
      'Academic Study Guides',
      'Competitive Exam Books (GATE/CAT/GRE)',
    ],
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600',
  },
  {
    id: 'electronics',
    name: 'Electronics',
    emoji: '💻',
    description: 'Laptop, tablet, calculator, projector, keyboard, mouse, headphones',
    subcategories: [
      'Laptops & MacBooks',
      'iPads & Tablets',
      'Scientific Calculators',
      'Mini Projectors',
      'Keyboards & Mice',
      'Noise-Canceling Headphones',
      'Monitors & Displays',
      'Power Banks & Chargers',
    ],
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600',
  },
  {
    id: 'science-lab',
    name: 'Science & Lab',
    emoji: '🧪',
    description: 'Lab coat, safety goggles, microscope, slides, lab/project equipment',
    subcategories: [
      'Lab Coats & Aprons',
      'Safety Goggles & Gloves',
      'Student Microscopes',
      'Prepared Glass Slides',
      'Glassware & Test Tubes',
      'Lab Pipettes & Burettes',
      'Project Equipment Kits',
    ],
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600',
  },
  {
    id: 'pharmacy',
    name: 'Pharmacy',
    emoji: '💊',
    description: 'Lab coat, reference books, pharmacy study models, educational lab equipment',
    subcategories: [
      'Pharmacy White Lab Coats',
      'Pharmacology Reference Books',
      'Anatomical & Chemical Study Models',
      'Educational Pharmacy Lab Equipment',
      'Spatulas & Pill Counting Trays',
      'Mortar and Pestle Sets',
    ],
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600',
  },
  {
    id: 'biotechnology',
    name: 'Biotechnology & Life Science',
    emoji: '🧬',
    description: 'Lab coat, microscope, educational models, project equipment',
    subcategories: [
      'Biotech Lab Coats',
      'Cellular Microscopes',
      'DNA & Molecular Model Kits',
      'Micropipettes (P20/P200/P1000)',
      'Petri Dishes & Culture Plates',
      'Bioinformatics & Genetics Books',
    ],
    image: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600',
  },
  {
    id: 'engineering',
    name: 'Engineering',
    emoji: '⚙️',
    description: 'Drafter, drawing board, calculator, Arduino, multimeter, project kits',
    subcategories: [
      'Mini Drafters with Sheet Bags',
      'Imperial Drawing Boards',
      'Scientific Graphing Calculators',
      'Arduino & Raspberry Pi Kits',
      'Digital Multimeters & Probes',
      'Breadboards & Electronic Components',
      'Soldering Station Kits',
      'Engineering Mechanics Kits',
    ],
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600',
  },
  {
    id: 'management-commerce',
    name: 'Management & Commerce',
    emoji: '📊',
    description: 'Presentation equipment, calculator, business books, project materials',
    subcategories: [
      'Wireless Presentation Clickers / Remotes',
      'Financial Calculators (HP/Texas Instruments)',
      'Harvard Business Case Studies & Books',
      'Marketing & Finance Textbooks',
      'Whiteboard & Presentation Stands',
      'Professional Portfolio Folders',
    ],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600',
  },
  {
    id: 'law',
    name: 'Law',
    emoji: '⚖️',
    description: 'Law books, reference materials, presentation equipment',
    subcategories: [
      'Constitution & Bare Acts',
      'Moot Court Robes & Advocates Collars',
      'Supreme Court Case Law Commentaries',
      'Legal Drafting Reference Books',
      'LexisNexis & SCC Online Guides',
      'Moot Court Presentation Lecterns',
    ],
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
  },
  {
    id: 'design-architecture',
    name: 'Design & Architecture',
    emoji: '🎨',
    description: 'Drawing board, art supplies, camera, tablet, design equipment',
    subcategories: [
      'Adjustable Architecture Drawing Tables',
      'Wacom / Drawing Graphic Tablets',
      'Rotring / Precision Technical Pens',
      'Scale Rulers & Cutting Mats',
      'DSLR Cameras for Site Photography',
      'Professional Acrylic & Watercolor Sets',
      '3D Scale Modeling Supplies',
    ],
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600',
  },
  {
    id: 'media-communication',
    name: 'Media & Communication',
    emoji: '🎬',
    description: 'Camera, tripod, microphone, lights, projector',
    subcategories: [
      'DSLR & Mirrorless Video Cameras',
      'Fluid-Head Video Tripods & Monopods',
      'Wireless Collar & Shotgun Microphones',
      'Ring Lights & Softbox Studio Lights',
      'Full HD Portable Projectors',
      'Audio Recorders (Zoom / Tascam)',
      'Gimbals & Camera Stabilizers',
    ],
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600',
  },
  {
    id: 'events-cultural',
    name: 'Events & Cultural',
    emoji: '🎤',
    description: 'Costumes, speakers, microphones, projector, decorations, props',
    subcategories: [
      'Stage & Drama Costumes',
      'Portable PA Bluetooth Party Speakers',
      'Wireless Handheld Microphones',
      'Stage Spotlights & Party Laser Lights',
      'Fest Decoration Lights & Backdrops',
      'Theatrical Drama Props',
    ],
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600',
  },
  {
    id: 'music',
    name: 'Music',
    emoji: '🎵',
    description: 'Guitar, keyboard, ukulele, microphone, amplifier',
    subcategories: [
      'Acoustic & Classical Guitars',
      'Electric Guitars & Bass Guitars',
      '61/88-Key Electronic Keyboards',
      'Concert Ukuleles with Gig Bags',
      'Guitar & Keyboard Amplifiers',
      'Studio Vocal Microphones & Pop Filters',
      'Cajons & Percussion Instruments',
    ],
    image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600',
  },
  {
    id: 'sports-fitness',
    name: 'Sports & Fitness',
    emoji: '🏏',
    description: 'Cricket kit, football, badminton racket, sports shoes, yoga mat',
    subcategories: [
      'Full Cricket Kits (Bat, Pads, Gloves, Helmet)',
      'Match Footballs & Shin Guards',
      'Carbon Graphite Badminton Rackets & Shuttles',
      'Table Tennis Bats & Balls',
      'Anti-Slip Yoga Mats & Foam Rollers',
      'Adjustable Dumbbells & Resistance Bands',
      'Basketballs & Volleyballs',
    ],
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600',
  },
  {
    id: 'formal-wear',
    name: 'Formal & Traditional Wear',
    emoji: '👔',
    description: 'Blazer, formal shoes, saree, traditional outfits, costumes',
    subcategories: [
      'Men Formal Blazers & Suits (Placement/Interviews)',
      'Oxford & Derby Formal Leather Shoes',
      'Traditional Sarees & Ethnic Lehengas',
      'Men Kurtas & Sherwanis (Campus Fests)',
      'Graduation Gowns & Robes',
      'Formal Ties, Belts & Cufflinks',
    ],
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600',
  },
  {
    id: 'hostel-life',
    name: 'Hostel & Student Life',
    emoji: '🏠',
    description: 'Table lamp, kettle, iron, extension board, study chair',
    subcategories: [
      'Electric Kettles & Hot Pots',
      'Induction Cooktops & Pans',
      'LED Study Table Lamps with Clamp',
      'Ergonomic Swivel Study Chairs',
      'Steam Irons & Ironing Boards',
      'Surge Protector Extension Spike Guards',
      'Cloth Drying Racks & Organizers',
      'Hostel Room Coolers & Fans',
    ],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600',
  },
  {
    id: 'travel',
    name: 'Travel',
    emoji: '🧳',
    description: 'Suitcase, travel backpack, camera bag, raincoat, camping items',
    subcategories: [
      'Hard-Shell Trolley Suitcases (Cabins & Check-in)',
      '50L-70L Trekking Backpacks with Rain Cover',
      'Padded DSLR Camera Bags',
      'Waterproof Raincoats & Windcheaters',
      'Camping Tents & Sleeping Bags',
      'Trekking Poles & Headlamps',
    ],
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    emoji: '🎮',
    description: 'Gaming console, controllers, board games, chess, speakers',
    subcategories: [
      'PlayStation & Xbox Consoles',
      'Wireless Gamepad Controllers',
      'VR Headsets (Meta Quest / PSVR)',
      'Board Games (Catan, Monopoly, Risk, Scrabble)',
      'Tournament Wooden Chess Sets',
      'Portable Party Karaoke Speakers',
      'Poker & Playing Card Sets',
    ],
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600',
  },
  {
    id: 'others',
    name: 'Others',
    emoji: '➕',
    description: 'Custom/miscellaneous items added by the seller that don’t fit any existing category',
    subcategories: [
      'Miscellaneous Campus Items',
      'Custom Student Projects',
      'Specialized Tools & Hardware',
      'Uncategorized Accessories',
      'Other Custom Item',
    ],
    image: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=600',
  },
];

export const getCategoryById = (id) => {
  return CATEGORIES.find((c) => c.id === id) || null;
};
