export const MOCK_POPULAR_ITEMS = [
  {
    id: 'item-1',
    title: 'Higher Engineering Mathematics - B.S. Grewal (44th Edition)',
    category: { id: 'books', name: 'Books' },
    price: 380,
    originalPrice: 850,
    condition: 'like-new',
    isNegotiable: true,
    location: 'Mechanical Dept / Central Library',
    campusLocation: 'Central Library Steps',
    timeAgo: '2 hours ago',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    ],
    seller: {
      name: 'Rohan Sharma',
      department: 'Mechanical Engg',
      semester: '6th Sem',
      rating: '4.9',
      isVerified: true,
    },
  },
  {
    id: 'item-2',
    title: 'Casio fx-991EX ClassWiz Scientific Calculator (Original with Cover)',
    category: { id: 'calculators', name: 'Calculators' },
    price: 850,
    originalPrice: 1695,
    condition: 'like-new',
    isNegotiable: false,
    location: 'Hostel Block B, Room 204',
    campusLocation: 'Hostel Block B',
    timeAgo: '4 hours ago',
    images: [
      'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=600&auto=format&fit=crop&q=80',
    ],
    seller: {
      name: 'Ananya Roy',
      department: 'Computer Science',
      semester: '4th Sem',
      rating: '5.0',
      isVerified: true,
    },
  },
  {
    id: 'item-3',
    title: 'Standard Lab Coat (Size M) + Chemistry Safety Goggles Kit',
    category: { id: 'lab-equipment', name: 'Lab Equipment' },
    price: 220,
    originalPrice: 550,
    condition: 'good',
    isNegotiable: true,
    location: 'Chemistry Dept, Room 102',
    campusLocation: 'Chemistry Block',
    timeAgo: '1 day ago',
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&auto=format&fit=crop&q=80',
    ],
    seller: {
      name: 'Pooja Nair',
      department: 'Biotechnology',
      semester: '3rd Sem',
      rating: '4.8',
      isVerified: true,
    },
  },
  {
    id: 'item-4',
    title: 'Hero Sprint Pro 26T Hybrid Bicycle with Front Basket & Lock',
    category: { id: 'cycles', name: 'Cycles' },
    price: 3200,
    originalPrice: 7800,
    condition: 'good',
    isNegotiable: true,
    location: 'Main Campus Cycle Stand',
    campusLocation: 'Main Gate Cycle Stand',
    timeAgo: '1 day ago',
    images: [
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&auto=format&fit=crop&q=80',
    ],
    seller: {
      name: 'Vikramaditya S.',
      department: 'Electrical Engg',
      semester: '8th Sem (Graduating)',
      rating: '4.9',
      isVerified: true,
    },
  },
  {
    id: 'item-5',
    title: 'Logitech K380 Multi-Device Bluetooth Wireless Keyboard',
    category: { id: 'laptop-accessories', name: 'Laptop Accessories' },
    price: 1400,
    originalPrice: 2895,
    condition: 'like-new',
    isNegotiable: false,
    location: 'Cafeteria / Innovation Center',
    campusLocation: 'Student Activity Center',
    timeAgo: '2 days ago',
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    ],
    seller: {
      name: 'Kavya Pillai',
      department: 'Information Tech',
      semester: '5th Sem',
      rating: '4.9',
      isVerified: true,
    },
  },
  {
    id: 'item-6',
    title: 'Engineering Mini Drafter + Engineering Drawing Board Set',
    category: { id: 'exam-materials', name: 'Exam Materials' },
    price: 450,
    originalPrice: 1200,
    condition: 'good',
    isNegotiable: true,
    location: 'Civil Dept Workshop',
    campusLocation: 'Civil Engineering Block',
    timeAgo: '3 days ago',
    images: [
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    ],
    seller: {
      name: 'Tanya Banerjee',
      department: 'Civil Engg',
      semester: '4th Sem',
      rating: '4.7',
      isVerified: true,
    },
  },
  {
    id: 'item-7',
    title: 'Pigeon 1.5L Stainless Steel Electric Kettle (Perfect for Hostel)',
    category: { id: 'hostel-items', name: 'Hostel Items' },
    price: 490,
    originalPrice: 1199,
    condition: 'like-new',
    isNegotiable: false,
    location: 'Hostel Block D Lobby',
    campusLocation: 'Hostel Block D',
    timeAgo: '3 days ago',
    images: [
      'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&auto=format&fit=crop&q=80',
    ],
    seller: {
      name: 'Deepak Patel',
      department: 'Chemical Engg',
      semester: '7th Sem',
      rating: '5.0',
      isVerified: true,
    },
  },
  {
    id: 'item-8',
    title: 'Yonex Nanoray Carbon Badminton Racket + 3 Shuttlecocks',
    category: { id: 'sports', name: 'Sports' },
    price: 750,
    originalPrice: 1850,
    condition: 'good',
    isNegotiable: true,
    location: 'Sports Complex / Indoor Court',
    campusLocation: 'Indoor Badminton Court',
    timeAgo: '4 days ago',
    images: [
      'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&auto=format&fit=crop&q=80',
    ],
    seller: {
      name: 'Aakash Verma',
      department: 'MBA',
      semester: '2nd Year',
      rating: '4.9',
      isVerified: true,
    },
  },
];

export const MOCK_STATISTICS = [
  { label: 'Students Joined', value: 8400, suffix: '+', description: 'Across verified campus domains' },
  { label: 'Items Listed', value: 14200, suffix: '+', description: 'Textbooks, tech, lab gear & cycles' },
  { label: 'Successful Exchanges', value: 11800, suffix: '+', description: 'Exchanged safely on campus' },
  { label: 'Colleges Connected', value: 42, suffix: '', description: 'Premier institutes & universities' },
];

export const MOCK_TESTIMONIALS = [
  {
    id: 'test-1',
    name: 'Siddharth Sen',
    college: 'National Institute of Technology',
    department: 'Computer Science, 4th Year',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    quote: 'Sold my semester textbooks within 30 minutes of posting! We met right outside the central cafeteria between lectures. No shipping hassles, no commission cuts.',
    rating: 5,
    tag: 'Quick Seller',
  },
  {
    id: 'test-2',
    name: 'Meera Deshmukh',
    college: 'Govt Engineering College',
    department: 'Electronics & Comm., 2nd Year',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    quote: 'Got a genuine scientific calculator and lab coat from a 4th-year senior at less than 40% of MRP. The verified college email requirement gave me complete peace of mind.',
    rating: 5,
    tag: 'Smart Buyer',
  },
  {
    id: 'test-3',
    name: 'Farhan Ali',
    college: 'Institute of Medical Sciences',
    department: 'MBBS, 3rd Year',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    quote: 'Bought a campus cycle for my daily commute between hostel and hospital wards. The in-app chat made it super easy to coordinate the meet-up time.',
    rating: 5,
    tag: 'Hostel Resident',
  },
];

export const MOCK_FAQS = [
  {
    id: 'faq-1',
    question: 'Who can use Campus Share?',
    answer: 'Campus Share is strictly exclusive to enrolled students, researchers, and faculty who possess a valid college email address (such as student@abccollege.edu). Every user is verified against approved college domains.',
  },
  {
    id: 'faq-2',
    question: 'How is my college verified during registration?',
    answer: 'When you sign up, you provide your official college email. We send an encrypted verification link to that address. Once clicked, your account is activated and mapped exclusively to your campus marketplace.',
  },
  {
    id: 'faq-3',
    question: 'Can I sell used books, notes, and drafters?',
    answer: 'Yes! Books, notes, calculators, lab coats, mini drafters, electronics, cycles, kettle/hostel items, and sports equipment are our most popular categories.',
  },
  {
    id: 'faq-4',
    question: 'How does in-app chat work?',
    answer: 'Our realtime Socket.io chat lets you message the seller directly within Campus Share. You can discuss the item condition, negotiate price, and agree on a convenient campus meeting spot (e.g. Library, Cafeteria, Hostel Gate).',
  },
  {
    id: 'faq-5',
    question: 'Does Campus Share handle online payments?',
    answer: 'Campus Share facilitates safe offline campus exchanges. Students meet in person at safe campus spots to inspect the item and settle payment directly via UPI, cash, or instant transfer without platform fees.',
  },
  {
    id: 'faq-6',
    question: 'How do seller ratings and reviews work?',
    answer: 'Once a seller marks an item as sold to a buyer, the buyer receives a prompt to rate the transaction from 1 to 5 stars with an optional review. This builds transparent community trust.',
  },
  {
    id: 'faq-7',
    question: 'How do I report a suspicious listing or spam user?',
    answer: 'Every listing has a "Report" flag button. You can choose reasons such as prohibited item, wrong details, or duplicate listing. Our campus moderation team reviews reports immediately.',
  },
];
